export const sampleJobs = [
  {
    id: "sample-1",
    title: "Senior Frontend Engineer",
    company: "Miro",
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    description: "Build collaborative product experiences with React, TypeScript, testing, and accessible design systems.",
    skills: ["React", "TypeScript", "JavaScript", "Testing"],
    role: "Engineering",
    sponsorship: true,
    remote: false,
    postedAt: "2026-09-08",
    url: "https://boards.greenhouse.io/miro",
    source: "Greenhouse",
  },
  {
    id: "sample-2",
    title: "Backend Engineer, Payments",
    company: "Mollie",
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    description: "Design reliable payment services using Java, Kotlin, AWS, event-driven systems, and PostgreSQL.",
    skills: ["Java", "Kotlin", "AWS", "PostgreSQL"],
    role: "Engineering",
    sponsorship: true,
    remote: true,
    postedAt: "2026-09-06",
    url: "https://www.mollie.com/careers",
    source: "Company site",
  },
  {
    id: "sample-3",
    title: "Product Data Analyst",
    company: "Contentful",
    location: "Berlin, Germany",
    country: "Germany",
    description: "Turn product data into decisions with SQL, Python, experimentation, dashboards, and stakeholder collaboration.",
    skills: ["SQL", "Python", "Tableau", "Analytics"],
    role: "Data",
    sponsorship: false,
    remote: true,
    postedAt: "2026-09-05",
    url: "https://www.contentful.com/careers/",
    source: "Lever",
  },
  {
    id: "sample-4",
    title: "DevOps Engineer",
    company: "Productboard",
    location: "Prague, Czechia",
    country: "Czechia",
    description: "Improve Kubernetes platforms, CI/CD pipelines, observability, and cloud infrastructure on AWS.",
    skills: ["Kubernetes", "AWS", "Terraform", "CI/CD"],
    role: "Engineering",
    sponsorship: true,
    remote: true,
    postedAt: "2026-09-04",
    url: "https://www.productboard.com/careers/",
    source: "Greenhouse",
  },
  {
    id: "sample-5",
    title: "UX Product Designer",
    company: "Storyblok",
    location: "Vienna, Austria",
    country: "Austria",
    description: "Shape intuitive content workflows through research, prototyping, Figma, and cross-functional product discovery.",
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems"],
    role: "Design",
    sponsorship: false,
    remote: true,
    postedAt: "2026-09-03",
    url: "https://www.storyblok.com/jobs",
    source: "Company site",
  },
  {
    id: "sample-6",
    title: "Security Engineer",
    company: "Collibra",
    location: "Brussels, Belgium",
    country: "Belgium",
    description: "Protect cloud products through threat modelling, security automation, Python tooling, and incident response.",
    skills: ["Security", "Python", "AWS", "Threat Modeling"],
    role: "Engineering",
    sponsorship: true,
    remote: false,
    postedAt: "2026-09-02",
    url: "https://www.collibra.com/us/en/company/careers",
    source: "Greenhouse",
  },
  {
    id: "sample-7",
    title: "Technical Account Manager",
    company: "Talkwalker",
    location: "Luxembourg, Luxembourg",
    country: "Luxembourg",
    description: "Guide enterprise customers through SaaS implementations, integrations, analytics, and technical enablement.",
    skills: ["SaaS", "APIs", "Analytics", "Customer Success"],
    role: "Customer Success",
    sponsorship: false,
    remote: false,
    postedAt: "2026-08-31",
    url: "https://www.talkwalker.com/careers",
    source: "Company site",
  },
  {
    id: "sample-8",
    title: "Machine Learning Engineer",
    company: "Innovatrics",
    location: "Bratislava, Slovakia",
    country: "Slovakia",
    description: "Develop production computer vision models with Python, PyTorch, MLOps, and scalable inference systems.",
    skills: ["Python", "PyTorch", "Machine Learning", "MLOps"],
    role: "Data",
    sponsorship: true,
    remote: false,
    postedAt: "2026-08-30",
    url: "https://www.innovatrics.com/careers/",
    source: "Company site",
  },
  {
    id: "sample-9",
    title: "Product Manager, B2B Platform",
    company: "Personio",
    location: "Munich, Germany",
    country: "Germany",
    description: "Lead platform strategy, discovery, roadmap delivery, metrics, and collaboration with engineering and design.",
    skills: ["Product Strategy", "Agile", "Analytics", "B2B SaaS"],
    role: "Product",
    sponsorship: true,
    remote: true,
    postedAt: "2026-08-28",
    url: "https://www.personio.com/about-personio/careers/",
    source: "Greenhouse",
  },
  {
    id: "sample-10",
    title: "Solutions Architect",
    company: "Datadog",
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    description: "Design cloud observability solutions across Kubernetes, AWS, APIs, and distributed systems for customers.",
    skills: ["AWS", "Kubernetes", "APIs", "Observability"],
    role: "Customer Success",
    sponsorship: false,
    remote: false,
    postedAt: "2026-08-26",
    url: "https://careers.datadoghq.com/",
    source: "Greenhouse",
  },
];
